server:
  port: 8080
  servlet:
    context-path: /identity
spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/identity_service"
    username: root
    password: 11111111
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
jwt:
  signerKey: "oqIC6eZm4jP/jX+JjfFKlPXthjv3zwWgC0kIu606yEYnR/z5zqQnZHAra5FRcEH3"
  valid-duration: 3600 # in second
  refreshable-duration: 360000 #in seconds


